networks:
  template_network-prod: # Change network name
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29 # Change ip if you want
services:
  template-prod: # change this depending on your project
    build:
      context: .
      dockerfile: Dockerfile-prod
    image: registry.brb.uz/template-department/template-image-prod
    container_name: template-prod
    ports:
      - 7070:7070 # Change port depending on your project
    networks:
      template_network-prod: # Change network name
        ipv4_address: 10.0.0.2 # Change ip if you want